# Generated by Django 5.0.6 on 2024-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guide_languages',
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_languages',
            field=models.ManyToManyField(to='Users.language'),
        ),
    ]
