# Generated by Django 5.0.6 on 2024-07-10 21:38

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('for_you', 'For You'), ('culture', 'Culture'), ('nature', 'Nature'), ('hotel', 'Hotel'), ('food', 'Food')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_type', models.CharField(choices=[('Mountainous', 'Mountainous Region'), ('Coastal', 'Coastal Region'), ('Desert', 'Desert Region'), ('Forest', 'Forest Region')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('name', models.CharField(default='Default Name', max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='Default description')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Wilayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.categorysite')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number in international format, starting with +213 or 0 followed by 9 digits.', max_length=128, null=True, region='DZ')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('item_type', models.CharField(max_length=100)),
                ('full_description', models.TextField()),
                ('highlight', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('time_string', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.categorysite')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.region')),
                ('wilayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.wilayat')),
            ],
        ),
    ]
