# Generated by Django 5.0.6 on 2024-07-04 17:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_language_remove_guide_guide_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='guide_languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ar', 'Arabic'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('it', 'Italian'), ('ko', 'Korean'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('pl', 'Polish'), ('vi', 'Vietnamese'), ('el', 'Greek'), ('th', 'Thai')], default='null', max_length=50),
            preserve_default=False,
        ),
    ]
