# Generated by Django 5.0.6 on 2024-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_guide_guide_languages_delete_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='guide_languages',
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_languages',
            field=models.ManyToManyField(related_name='guides', to='Users.language'),
        ),
    ]
