# Generated by Django 5.0.6 on 2024-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_user',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
