# Generated by Django 5.0.6 on 2024-07-18 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_client_email_user_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='alger', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='firstname',
            field=models.CharField(default='nn', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='lastname',
            field=models.CharField(default='cc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(default=123456789, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='wilaya',
            field=models.CharField(default='alger', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
