# Generated by Django 5.0.6 on 2024-07-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_dailyactivity_onedayactivity_oneweekactivity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyActivity',
        ),
        migrations.DeleteModel(
            name='OneDayActivity',
        ),
        migrations.DeleteModel(
            name='OneWeekActivity',
        ),
        migrations.DeleteModel(
            name='SpecificDurationActivity',
        ),
    ]
