# Generated by Django 5.0.6 on 2024-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_booking_firstname_alter_booking_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
