# Generated by Django 5.0.6 on 2024-07-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_dailyactivity_onedayactivity_oneweekactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybase',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='price',
            name='activity',
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
        migrations.DeleteModel(
            name='OneDayActivity',
        ),
        migrations.DeleteModel(
            name='OneWeekActivity',
        ),
        migrations.DeleteModel(
            name='SpecificDurationActivity',
        ),
        migrations.DeleteModel(
            name='ActivityBase',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
