# Generated by Django 5.0.6 on 2024-07-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_agency_agency_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='verification_code',
        ),
    ]
