# Generated by Django 5.0.6 on 2024-07-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_activitybase_dailyactivity_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybase',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='activity_base',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ActivityBase',
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
    ]
