# Generated by Django 5.0.6 on 2024-07-12 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_remove_activitybase_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_phone', models.CharField(max_length=20)),
                ('activity_type', models.CharField(max_length=255)),
                ('activity_description', models.TextField()),
                ('activity_location', models.URLField()),
                ('emergency_phone_number', models.CharField(max_length=20)),
                ('cut_off_time', models.CharField(max_length=20)),
                ('meeting_point', models.URLField()),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_activities', to=settings.AUTH_USER_MODEL)),
                ('activity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.activitycategory')),
                ('food', models.ManyToManyField(to='Users.food')),
                ('transport', models.ManyToManyField(to='Users.transport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
