# Generated by Django 5.0.6 on 2024-07-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_activitycategory_food_transport_activitybase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], max_length=50)),
                ('number_of_clients', models.IntegerField()),
                ('price', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Users.activitybase')),
            ],
        ),
    ]
